### ISSUE TITLE
Passing hardcoded numeric value like 50 results in 200 response, but passsing a long or int64_t data type, results in 400 response

### ISSUE THREAD

**Issue by dinob68** [microsoft/cpprestsdk#1508]
My Swagger document defines a long data type expected to be sent in a request like:

```
    size:
      type: integer
      format: int64
      description: 'Some size'
```

I create request using following code in C++:

`web::json::value postData = web::json::value::object();`

If I pass a hardcoded value in body as below, I get 200 OK, so that is good
`postData[L"size"] = web::json::value::number(50);`

However, if I pass this value as a long or int64_t data type like below, I get 400 Bad Request 
```
long size = 50;   //or int64_t, it results with same error
postData[L"size"] = web::json::value::number(size);
```
